### ISSUE TITLE
Latest json problem

### ISSUE THREAD

**Issue by K4ryuu** [ByMykel/counter-strike-price-tracker#2]
The latest json has like 60 skins overall and the rest is missing

**Comment by ByMykel** [comment]
Seems like It's getting rate limited. I'll try to limit the requests per minute, but I'm unsure of what is the limit. I can't find a unique answer.

**Comment by ByMykel** [comment]
I've reverted the last three commits. You'll see the prices but not updated.

I've also limited the requests to 30 per minute and will test it now.

**Comment by ByMykel** [comment]
Should be fixed now.
